### PR TITLE
Feature/pooja tensor

### PR DESCRIPTION
**Pull request by thepoojashetty**

### CODE REVIEW

**Comment by usmanklodhi** [comment]
@thepoojashetty can you please add PR description detailing what changes have been made?

**Comment by thepoojashetty** [comment]
> @thepoojashetty can you please add PR description detailing what changes have been made?

Implemented all functionalities for matvec but test case seem to fail. Receiving segmentation fault.

**Comment by thepoojashetty** [comment]
> No description provided.

The latest commit : [all test cases passing for tensor, segmentation fault for matvec](https://github.com/usmanklodhi/advpt-exercises/pull/10/commits/fbf22728e4cff1135bf976b22c360cfbd7c40c1a)

All test cases for tensor are now passing
Matvec is still failing

**Comment by thepoojashetty** [comment]
All the test cases for both tensor and marvel are now passing

**Review by usmanklodhi — APPROVED** [review]
LGTM!

**Pull request merged**
